.\" zygo/zygo.1
.\"
.\" Copyright (c) 2022 hhvn <dev@hhvn.uk>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

.Dd COMMIT
.Dt zygo 1
.Os
.Sh NAME
.Nm zygo
.Nd ncurses gopher client
.Sh SYNOPSIS
.Nm
.Op Fl kv
.Op Ar uri
.Sh DESCRIPTION
.Nm
is a rewrite of
.Xr cgo 1
that tidies up a lot of stuff,
and has pager functionality using ncurses.
.Ss TLS
.Nm
supports gopher over TLS using the gophers:// uri schema.
If a gopher menu is accessed over TLS, 
any links to the same server and port will be accessed over TLS.

.Nm
will also attempt to upgrade connections to TLS when it encounters a new server
if it is invoked with the
.Fl u
flag, or if the
.Ar autotls
variable is set in
.Ar config.h "."
.Ss Name
.Nm
is taken from the first four letters of the gopher genus Zygogeomys.
.Ss Plumber
The plumber is a program that is run with a link as the first argument when
.Nm
cannot display a link. The program used for this may be changed in
.Ar config.h ","
or by using the
.Fl p
flag.

By default
.Nm
will temporarily leave curses mode to allow the plumber access to the terminal.
This can be disabled by setting the
.Ar parallelplumb
variable in
.Ar config.h ","
or by using the
.Fl P
flag.
.Sh OPTIONS
.Bl -compact -tag -width "-p plumber"
.It Fl v
Print version info.
.It Fl k
Turn off certificate checking for TLS.
.It Fl p Ar plumber
Set the plumber to
.Ar plumber "."
.It Fl P
Do not wait for the plumber to exit.
.It Fl u
Automatically upgrade connections to TLS.
.It Fl
.Sh INPUT
.Nm
is constantly reading input.
This input can be either an id to a link
(seen to the left of a line) or a command.
If a command requires an argument,
or the id is ambiguous,
the user must press enter.
.Sh COMMANDS
.Bl -compact -tag -width "       "
.It : Ar uri
Go to
.Ar uri "."
.It / Ar query
Search forwards for
.Ar query "."
.It ? Ar query
Search backwards for
.Ar query "."
.It n
Search forwards with already present query.
.It N
Search backwards with already present query.
.It a Ar path
Append
.Ar path
to the current uri.
.It j
Scroll down one line.
.It ^D
Scroll down half a page.
.It k
Scroll up one line.
.It ^U
Scroll up half a page.
.It q
Quit.
.It <
Go back in history.
.It *
Reload page.
.It g
Go to top of page.
.It G
Go to bottom of page.
.It r
Go to root selector of current gopherhole.
.It +
Print uri of link where the bar normally is.
.El
.Sh SEE OTHER
.Xr cgo 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk 
